export const ErrorCodes = {
  THREADS_TOKEN_EXPIRED: 'THREADS_TOKEN_EXPIRED',
  THREADS_ACCOUNT_PRIVATE: 'THREADS_ACCOUNT_PRIVATE',
  THREADS_ACCOUNT_NOT_FOUND: 'THREADS_ACCOUNT_NOT_FOUND',
  THREADS_RATE_LIMITED: 'THREADS_RATE_LIMITED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  NO_DATA_FOUND: 'NO_DATA_FOUND',
  FIELD_UNAVAILABLE: 'FIELD_UNAVAILABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
